## Name: Gaurav Kedia
## Roll No. : E-39


In [3]:
import nltk
from nltk.corpus import brown
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import PCA


In [4]:
nltk.download('brown')
chapters = brown.categories()

[nltk_data] Error loading brown: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


In [5]:
# Generate document term matrix for each chapter
document_term_matrices = []
for chapter in chapters:
    chapter_docs = brown.fileids(categories=chapter)
    chapter_texts = [brown.raw(fileid) for fileid in chapter_docs]
    vectorizer = CountVectorizer(lowercase=True, stop_words='english')
    X = vectorizer.fit_transform(chapter_texts)
    document_term_matrices.append(X.toarray())



In [6]:
print(document_term_matrices)

[array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64), array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64), array([[3, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 1, 0, 1],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64), array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64), array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0

In [8]:
# Store document term matrices in a dictionary with chapter names as keys
document_term_matrix_dict = {chapter: dtm for chapter, dtm in zip(chapters, document_term_matrices)}


In [9]:
print(document_term_matrix_dict)

{'adventure': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64), 'belles_lettres': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64), 'editorial': array([[3, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 1, 0, 1],
       [0, 0, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64), 'fiction': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64), 'government': array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 

In [10]:
# Access document term matrix for a specific chapter
chapter_name = "news"
dtm = document_term_matrix_dict[chapter_name]
print("Document Term Matrix for Chapter {}: ".format(chapter_name))
print(dtm)

Document Term Matrix for Chapter news: 
[[0 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 ...
 [4 0 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 [7 0 0 ... 0 0 0]]
